// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cron.sql

package repository

import (
	"context"
)

const findAll = `-- name: FindAll :many
SELECT id, name, command, created_at, updated_at FROM tasks
`

func (q *Queries) FindAll(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, findAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Command,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByID = `-- name: FindByID :one
SELECT id, name, command, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) FindByID(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, findByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findByName = `-- name: FindByName :one
SELECT id, name, command, created_at, updated_at FROM tasks WHERE name = ?
`

func (q *Queries) FindByName(ctx context.Context, name string) (Task, error) {
	row := q.db.QueryRowContext(ctx, findByName, name)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateName = `-- name: UpdateName :exec
UPDATE tasks SET name = ? WHERE id = ?
`

type UpdateNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateName(ctx context.Context, arg UpdateNameParams) error {
	_, err := q.db.ExecContext(ctx, updateName, arg.Name, arg.ID)
	return err
}
