// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type CronJob struct {
	ID        int64
	Name      string
	Schedule  string
	Command   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
