// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Task struct {
	ID        int64
	Name      string
	Command   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TaskAssignment struct {
	ID          int64
	ContainerID string
	TaskID      int64
	Schedule    string
	Active      sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
