// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type Task struct {
	ID        int64
	Name      string
	Command   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
